services:
  - type: web
    name: segprosst
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn segprosst.wsgi:application

