# Generated by Django 4.2.23 on 2025-07-26 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateField(auto_now_add=True)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('assinatura_confirmada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Entrega de EPI',
                'verbose_name_plural': 'Entregas de EPI',
                'ordering': ['-data_entrega'],
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('validade_meses', models.PositiveIntegerField(default=12)),
                ('quantidade_estoque', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('cargo', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LogEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('acao', models.TextField()),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epi.entregaepi')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='entregaepi',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epi.equipamento'),
        ),
        migrations.AddField(
            model_name='entregaepi',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epi.funcionario'),
        ),
        migrations.AddField(
            model_name='entregaepi',
            name='responsavel_entrega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
